kind: Namespace
apiVersion: v1
metadata:
  name: hello-rancher
---
apiVersion: v1
kind: Service
metadata:
  name: hello-rancher
  namespace: hello-rancher
spec:
  type: NodePort
  selector:
    app: hello-rancher
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rancher
  namespace: hello-rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-rancher
  template:
    metadata:
      labels:
        app: hello-rancher
    spec:
      containers:
        - name: hello-rancher
          image: sharkshashi/hello-rancher:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: CONTAINER_COLOR
              value: red
            - name: TITLE
              value: Hello Rancher              
            - name: PETS
              value: chameleon   
          readinessProbe:
            httpGet:
              port: web
              path: /
